apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-profile-service
  namespace: exalt-shared
  labels:
    app: user-profile-service
    component: infrastructure
    domain: shared
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user-profile-service
  template:
    metadata:
      labels:
        app: user-profile-service
        component: infrastructure
        domain: shared
    spec:
      containers:
      - name: user-profile-service
        image: exalt/user-profile-service:latest
        ports:
        - containerPort: 8095
          name: http
        - containerPort: 9090
          name: metrics
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "production"
        - name: SERVER_PORT
          value: "8095"
        - name: DB_HOST
          value: "postgres-service"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "user_profile_db"
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: user-profile-secrets
              key: db-username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: user-profile-secrets
              key: db-password
        - name: REDIS_HOST
          value: "redis-service"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_DATABASE
          value: "14"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: user-profile-secrets
              key: jwt-secret
        - name: ELASTICSEARCH_HOST
          value: "elasticsearch-service"
        - name: ELASTICSEARCH_PORT
          value: "9200"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: user-profile-secrets
              key: aws-access-key-id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: user-profile-secrets
              key: aws-secret-access-key
        - name: FACEBOOK_APP_SECRET
          valueFrom:
            secretKeyRef:
              name: user-profile-secrets
              key: facebook-app-secret
        - name: GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: user-profile-secrets
              key: google-client-secret
        - name: TWITTER_API_SECRET
          valueFrom:
            secretKeyRef:
              name: user-profile-secrets
              key: twitter-api-secret
        - name: LINKEDIN_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: user-profile-secrets
              key: linkedin-client-secret
        - name: EUREKA_SERVER_URL
          value: "http://service-registry:8761/eureka"
        - name: AUTH_SERVICE_URL
          value: "http://auth-service:8080"
        - name: NOTIFICATION_SERVICE_URL
          value: "http://notification-service:8091"
        - name: KYC_SERVICE_URL
          value: "http://kyc-service:8088"
        - name: FILE_STORAGE_SERVICE_URL
          value: "http://file-storage-service:8086"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8095
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8095
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        volumeMounts:
        - name: user-avatars
          mountPath: /var/user-profiles/avatars
      volumes:
      - name: user-avatars
        persistentVolumeClaim:
          claimName: user-avatars-pvc
      restartPolicy: Always