apiVersion: v1
kind: Service
metadata:
  name: user-profile-service
  namespace: exalt-shared
  labels:
    app: user-profile-service
    component: infrastructure
    domain: shared
spec:
  type: ClusterIP
  ports:
  - port: 8095
    targetPort: 8095
    protocol: TCP
    name: http
  - port: 9090
    targetPort: 9090
    protocol: TCP
    name: metrics
  selector:
    app: user-profile-service

---
apiVersion: v1
kind: Service
metadata:
  name: user-profile-service-external
  namespace: exalt-shared
  labels:
    app: user-profile-service
    component: infrastructure
    domain: shared
spec:
  type: LoadBalancer
  ports:
  - port: 8095
    targetPort: 8095
    protocol: TCP
    name: http
  selector:
    app: user-profile-service