apiVersion: v1
kind: ConfigMap
metadata:
  name: caching-service-config
  namespace: exalt-shared
  labels:
    app: caching-service
    component: infrastructure
    domain: shared
data:
  application-k8s.yml: |
    server:
      port: 8403
    
    spring:
      application:
        name: caching-service
      profiles:
        active: k8s
      redis:
        host: redis-service
        port: 6379
        timeout: 60000ms
        lettuce:
          pool:
            max-active: 8
            max-wait: -1ms
            max-idle: 8
            min-idle: 0
    
    cache:
      caffeine:
        spec: maximumSize=1000,expireAfterWrite=10m
      redis:
        default-ttl: 3600
        ttl:
          user-cache: 1800
          session-cache: 900
          product-cache: 7200
    
    management:
      endpoints:
        web:
          exposure:
            include: health,info,metrics,prometheus,caches
      endpoint:
        health:
          show-details: always
      metrics:
        export:
          prometheus:
            enabled: true
    
    logging:
      level:
        com.exalt.ecosystem.shared.caching: INFO
        org.springframework.cache: DEBUG
        org.springframework.data.redis: DEBUG