apiVersion: apps/v1
kind: Deployment
metadata:
  name: caching-service
  namespace: shared-infrastructure
  labels:
    app: caching-service
    domain: shared-infrastructure
spec:
  replicas: 3
  selector:
    matchLabels:
      app: caching-service
  template:
    metadata:
      labels:
        app: caching-service
    spec:
      containers:
      - name: caching-service
        image: social-ecommerce-ecosystem/caching-service:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "kubernetes"
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://service-registry:8761/eureka/"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 5
        resources:
          limits:
            memory: "1Gi"
            cpu: "500m"
          requests:
            memory: "512Mi"
            cpu: "250m"
