server:
  port: 8081

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:h2:mem:authdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.exalt: DEBUG
    org.springframework.security: DEBUG

jwt:
  secret: ${JWT_SECRET:#{null}}
  expiration: ${JWT_EXPIRATION:3600000}  # 1 hour default
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:7200000}  # 2 hours default

# SECURITY FIX: Password Encryption Configuration (CVSS 9.1)
security:
  password:
    bcrypt:
      strength: ${BCRYPT_STRENGTH:12}  # BCrypt rounds (recommended: 12-15)
    min-length: ${PASSWORD_MIN_LENGTH:12}
    require-uppercase: ${PASSWORD_REQUIRE_UPPERCASE:true}
    require-lowercase: ${PASSWORD_REQUIRE_LOWERCASE:true}
    require-numbers: ${PASSWORD_REQUIRE_NUMBERS:true}
    require-special-chars: ${PASSWORD_REQUIRE_SPECIAL_CHARS:true}
    history-count: ${PASSWORD_HISTORY_COUNT:5}  # Number of previous passwords to remember
    expiry-days: ${PASSWORD_EXPIRY_DAYS:90}  # Password expiration in days
    max-failed-attempts: ${MAX_FAILED_ATTEMPTS:5}
    lockout-duration-minutes: ${LOCKOUT_DURATION_MINUTES:30}
