name: Deploy to Development

on:
  push:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Development Environment
    runs-on: ubuntu-latest
    environment: development

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Run tests
        run: mvn test

      - name: Build application
        run: mvn clean package -DskipTests

      - name: Build Docker image
        run: |
          docker build -t gogidix/document-verification:dev-${{ github.sha }} .
          docker tag gogidix/document-verification:dev-${{ github.sha }} gogidix/document-verification:dev-latest

      - name: Login to Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Push Docker image
        run: |
          docker push gogidix/document-verification:dev-${{ github.sha }}
          docker push gogidix/document-verification:dev-latest

      - name: Deploy to Kubernetes
        uses: azure/k8s-deploy@v1
        with:
          namespace: exalt-dev
          manifests: |
            k8s/deployment.yaml
            k8s/service.yaml
            k8s/hpa.yaml
            k8s/configmap.yaml
          images: |
            gogidix/document-verification:dev-${{ github.sha }}

      - name: Wait for deployment
        run: |
          kubectl rollout status deployment/document-verification -n exalt-dev --timeout=300s

      - name: Run smoke tests
        run: |
          DOC_VERIFY_URL=$(kubectl get service document-verification -n exalt-dev -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
          if [ -z "$DOC_VERIFY_URL" ]; then
            DOC_VERIFY_URL=$(kubectl get service document-verification -n exalt-dev -o jsonpath='{.spec.clusterIP}')
          fi
          curl -f http://$DOC_VERIFY_URL:8085/actuator/health || exit 1
          echo "Smoke tests passed!"

      - name: Notify deployment status
        if: always()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          text: |
            Document Verification Service deployment to development: ${{ job.status }}
            Commit: ${{ github.sha }}
            Branch: ${{ github.ref }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}