server:
  port: 8761

spring:
  application:
    name: service-registry
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

eureka:
  instance:
    hostname: ${EUREKA_HOSTNAME:localhost}
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false
    renewal-percent-threshold: 0.85

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

logging:
  level:
    com.exalt: INFO
    com.netflix.eureka: WARN
    com.netflix.discovery: WARN
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

info:
  app:
    name: ${spring.application.name}
    description: Eureka Service Registry for microservices discovery
    version: 1.0.0
    encoding: UTF-8
    java:
      version: ${java.version}