apiVersion: v1
kind: Service
metadata:
  name: currency-exchange-service
  namespace: exalt-shared
  labels:
    app: currency-exchange-service
    component: infrastructure
    domain: shared
spec:
  type: ClusterIP
  ports:
  - port: 8082
    targetPort: 8082
    protocol: TCP
    name: http
  - port: 8083
    targetPort: 8083
    protocol: TCP
    name: admin
  selector:
    app: currency-exchange-service