name: API Gateway Build and Test

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'social-ecommerce-ecosystem/shared-infrastructure/api-gateway/**'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'social-ecommerce-ecosystem/shared-infrastructure/api-gateway/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: social-ecommerce-ecosystem/shared-infrastructure/api-gateway
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Run tests
      run: mvn test
    
    - name: Build Docker image
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
      run: |
        docker build -t api-gateway:${GITHUB_SHA::8} .
    
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

