openapi: 3.0.3
info:
  title: "User Profile Service API"
  description: "RESTful API for User Profile Service service"
  version: "1.0.0"
servers:
  - url: "http://localhost:TBD/api/v1"
paths:
  /health:
    get:
      summary: "Health check"
      responses:
        '200':
          description: "Service is healthy"
