openapi: 3.0.3
info:
  title: Config Server API
  description: API for config-server
  version: 1.0.0
paths:
  /actuator/health:
    get:
      summary: Health check
      responses:
        '200':
          description: Service is healthy
