apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-engine
  namespace: exalt-shared
  labels:
    app: analytics-engine
    component: infrastructure
    domain: shared
spec:
  replicas: 2
  selector:
    matchLabels:
      app: analytics-engine
  template:
    metadata:
      labels:
        app: analytics-engine
        component: infrastructure
        domain: shared
    spec:
      containers:
      - name: analytics-engine
        image: exalt/analytics-engine:latest
        ports:
        - containerPort: 8096
          name: http
        - containerPort: 9090
          name: metrics
        - containerPort: 4040
          name: spark-ui
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "production"
        - name: SERVER_PORT
          value: "8096"
        - name: DB_HOST
          value: "postgres-service"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "analytics_db"
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: analytics-secrets
              key: db-username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: analytics-secrets
              key: db-password
        - name: REDIS_HOST
          value: "redis-service"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_DATABASE
          value: "15"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: analytics-secrets
              key: jwt-secret
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-service:9092"
        - name: CLICKHOUSE_HOST
          value: "clickhouse-service"
        - name: CLICKHOUSE_PORT
          value: "8123"
        - name: CLICKHOUSE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: analytics-secrets
              key: clickhouse-password
        - name: ELASTICSEARCH_HOST
          value: "elasticsearch-service"
        - name: ELASTICSEARCH_PORT
          value: "9200"
        - name: ELASTICSEARCH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: analytics-secrets
              key: elasticsearch-password
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: analytics-secrets
              key: aws-access-key-id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: analytics-secrets
              key: aws-secret-access-key
        - name: EUREKA_SERVER_URL
          value: "http://service-registry:8761/eureka"
        - name: SPARK_MASTER
          value: "k8s://https://kubernetes.default.svc:443"
        - name: SPARK_EXECUTOR_INSTANCES
          value: "2"
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8096
          initialDelaySeconds: 90
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8096
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        volumeMounts:
        - name: analytics-models
          mountPath: /app/models
        - name: analytics-reports
          mountPath: /var/analytics/reports
      volumes:
      - name: analytics-models
        persistentVolumeClaim:
          claimName: analytics-models-pvc
      - name: analytics-reports
        persistentVolumeClaim:
          claimName: analytics-reports-pvc
      restartPolicy: Always