apiVersion: v1
kind: Service
metadata:
  name: analytics-engine
  namespace: exalt-shared
  labels:
    app: analytics-engine
    component: infrastructure
    domain: shared
spec:
  type: ClusterIP
  ports:
  - port: 8096
    targetPort: 8096
    protocol: TCP
    name: http
  - port: 9090
    targetPort: 9090
    protocol: TCP
    name: metrics
  - port: 4040
    targetPort: 4040
    protocol: TCP
    name: spark-ui
  selector:
    app: analytics-engine

---
apiVersion: v1
kind: Service
metadata:
  name: analytics-engine-external
  namespace: exalt-shared
  labels:
    app: analytics-engine
    component: infrastructure
    domain: shared
spec:
  type: LoadBalancer
  ports:
  - port: 8096
    targetPort: 8096
    protocol: TCP
    name: http
  - port: 4040
    targetPort: 4040
    protocol: TCP
    name: spark-ui
  selector:
    app: analytics-engine