apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: config-server-hpa
  namespace: exalt-shared
  labels:
    app: config-server
    component: infrastructure
    domain: shared
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: config-server
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60