name: Deploy to Development

on:
  push:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Development Environment
    runs-on: ubuntu-latest
    environment: development

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Build Docker image
        run: |
          docker build -t gogidix/billing-engine:dev-${{ github.sha }} .
          docker tag gogidix/billing-engine:dev-${{ github.sha }} gogidix/billing-engine:dev-latest

      - name: Login to Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Push Docker image
        run: |
          docker push gogidix/billing-engine:dev-${{ github.sha }}
          docker push gogidix/billing-engine:dev-latest

      - name: Deploy to Kubernetes
        uses: azure/k8s-deploy@v1
        with:
          namespace: exalt-dev
          manifests: |
            k8s/deployment.yaml
            k8s/service.yaml
            k8s/hpa.yaml
          images: |
            gogidix/billing-engine:dev-${{ github.sha }}

      - name: Wait for deployment
        run: |
          kubectl rollout status deployment/billing-engine -n exalt-dev --timeout=300s

      - name: Run smoke tests
        run: |
          BILLING_URL=$(kubectl get service billing-engine -n exalt-dev -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
          if [ -z "$BILLING_URL" ]; then
            BILLING_URL=$(kubectl get service billing-engine -n exalt-dev -o jsonpath='{.spec.clusterIP}')
          fi
          curl -f http://$BILLING_URL:8080/health || exit 1
          echo "Smoke tests passed!"

      - name: Notify deployment status
        if: always()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          text: |
            Billing Engine deployment to development: ${{ job.status }}
            Commit: ${{ github.sha }}
            Branch: ${{ github.ref }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}