apiVersion: apps/v1
kind: Deployment
metadata:
  name: logging-service
  namespace: shared-infrastructure
spec:
  replicas: 2
  selector:
    matchLabels:
      app: logging-service
  template:
    metadata:
      labels:
        app: logging-service
    spec:
      containers:
      - name: logging-service
        image: exalt-ecosystem/logging-service:latest
        ports:
        - containerPort: 8759
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "kubernetes"
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://service-registry:8761/eureka/"
        - name: SPRING_CLOUD_CONFIG_URI
          value: "http://config-server:8888"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8759
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8759
          initialDelaySeconds: 30
          periodSeconds: 5