apiVersion: v1
kind: ConfigMap
metadata:
  name: message-broker-config
  namespace: shared-infrastructure
data:
  application.yml: |
    spring:
      application:
        name: message-broker
      profiles:
        active: kubernetes
    eureka:
      client:
        serviceUrl:
          defaultZone: http://service-registry:8761/eureka/
    management:
      endpoints:
        web:
          exposure:
            include: health,info,metrics
