apiVersion: v1
kind: Service
metadata:
  name: message-broker
  namespace: shared-infrastructure
  labels:
    app: message-broker
spec:
  selector:
    app: message-broker
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
