openapi: 3.0.3
info:
  title: "Service Registry API"
  description: "RESTful API for Service Registry service"
  version: "1.0.0"
servers:
  - url: "http://localhost:8411/api/v1"
paths:
  /health:
    get:
      summary: "Health check"
      responses:
        '200':
          description: "Service is healthy"
