apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: exalt-shared
  labels:
    app: auth-service
    component: infrastructure
    domain: shared
spec:
  type: ClusterIP
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
    name: http
  - port: 9090
    targetPort: 9090
    protocol: TCP
    name: metrics
  selector:
    app: auth-service

---
apiVersion: v1
kind: Service
metadata:
  name: auth-service-external
  namespace: exalt-shared
  labels:
    app: auth-service
    component: infrastructure
    domain: shared
spec:
  type: LoadBalancer
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
    name: http
  selector:
    app: auth-service