apiVersion: v1
kind: Service
metadata:
  name: service-registry
  namespace: exalt-shared
  labels:
    app: service-registry
    component: infrastructure
    domain: shared
spec:
  type: ClusterIP
  ports:
  - port: 8761
    targetPort: 8761
    protocol: TCP
    name: http
  selector:
    app: service-registry

---
apiVersion: v1
kind: Service
metadata:
  name: service-registry-external
  namespace: exalt-shared
  labels:
    app: service-registry
    component: infrastructure
    domain: shared
spec:
  type: LoadBalancer
  ports:
  - port: 8761
    targetPort: 8761
    protocol: TCP
    name: http
  selector:
    app: service-registry