apiVersion: v1
kind: Service
metadata:
  name: ui-design-system
  namespace: exalt-shared
  labels:
    app: ui-design-system
    component: infrastructure
    domain: shared
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: ui-design-system

---
apiVersion: v1
kind: Service
metadata:
  name: ui-design-system-external
  namespace: exalt-shared
  labels:
    app: ui-design-system
    component: infrastructure
    domain: shared
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: ui-design-system