apiVersion: v1
kind: Service
metadata:
  name: geo-location-service
  namespace: exalt-shared
  labels:
    app: geo-location-service
    component: infrastructure
    domain: shared
spec:
  type: ClusterIP
  ports:
  - port: 8087
    targetPort: 8087
    protocol: TCP
    name: http
  - port: 9090
    targetPort: 9090
    protocol: TCP
    name: metrics
  selector:
    app: geo-location-service

---
apiVersion: v1
kind: Service
metadata:
  name: geo-location-service-external
  namespace: exalt-shared
  labels:
    app: geo-location-service
    component: infrastructure
    domain: shared
spec:
  type: LoadBalancer
  ports:
  - port: 8087
    targetPort: 8087
    protocol: TCP
    name: http
  selector:
    app: geo-location-service