apiVersion: v1
kind: Service
metadata:
  name: tracing-config
  namespace: exalt-shared
  labels:
    app: tracing-config
    component: infrastructure
    domain: shared
spec:
  type: ClusterIP
  ports:
  - port: 8093
    targetPort: 8093
    protocol: TCP
    name: http
  - port: 9090
    targetPort: 9090
    protocol: TCP
    name: metrics
  - port: 14268
    targetPort: 14268
    protocol: TCP
    name: jaeger-http
  - port: 14250
    targetPort: 14250
    protocol: TCP
    name: jaeger-grpc
  - port: 6831
    targetPort: 6831
    protocol: UDP
    name: jaeger-udp
  - port: 6832
    targetPort: 6832
    protocol: UDP
    name: jaeger-compact
  selector:
    app: tracing-config

---
apiVersion: v1
kind: Service
metadata:
  name: tracing-config-external
  namespace: exalt-shared
  labels:
    app: tracing-config
    component: infrastructure
    domain: shared
spec:
  type: LoadBalancer
  ports:
  - port: 8093
    targetPort: 8093
    protocol: TCP
    name: http
  - port: 14268
    targetPort: 14268
    protocol: TCP
    name: jaeger-http
  selector:
    app: tracing-config