apiVersion: v1
kind: Service
metadata:
  name: message-broker
  namespace: exalt-shared
  labels:
    app: message-broker
    component: infrastructure
    domain: shared
spec:
  type: ClusterIP
  ports:
  - port: 8089
    targetPort: 8089
    protocol: TCP
    name: http
  - port: 9090
    targetPort: 9090
    protocol: TCP
    name: metrics
  - port: 9999
    targetPort: 9999
    protocol: TCP
    name: jmx
  selector:
    app: message-broker

---
apiVersion: v1
kind: Service
metadata:
  name: message-broker-external
  namespace: exalt-shared
  labels:
    app: message-broker
    component: infrastructure
    domain: shared
spec:
  type: LoadBalancer
  ports:
  - port: 8089
    targetPort: 8089
    protocol: TCP
    name: http
  selector:
    app: message-broker