apiVersion: v1
kind: Service
metadata:
  name: config-server
  namespace: shared-infrastructure
  labels:
    app: config-server
spec:
  selector:
    app: config-server
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
