apiVersion: v1
kind: Service
metadata:
  name: translation-service
  namespace: exalt-shared
  labels:
    app: translation-service
    component: infrastructure
    domain: shared
spec:
  type: ClusterIP
  ports:
  - port: 8094
    targetPort: 8094
    protocol: TCP
    name: http
  - port: 9090
    targetPort: 9090
    protocol: TCP
    name: metrics
  selector:
    app: translation-service

---
apiVersion: v1
kind: Service
metadata:
  name: translation-service-external
  namespace: exalt-shared
  labels:
    app: translation-service
    component: infrastructure
    domain: shared
spec:
  type: LoadBalancer
  ports:
  - port: 8094
    targetPort: 8094
    protocol: TCP
    name: http
  selector:
    app: translation-service