apiVersion: v1
kind: Service
metadata:
  name: admin-frameworks
  namespace: exalt-shared
  labels:
    app: admin-frameworks
    component: infrastructure
    domain: shared
spec:
  type: ClusterIP
  ports:
  - port: 8097
    targetPort: 8097
    protocol: TCP
    name: http
  - port: 9090
    targetPort: 9090
    protocol: TCP
    name: metrics
  selector:
    app: admin-frameworks

---
apiVersion: v1
kind: Service
metadata:
  name: admin-frameworks-external
  namespace: exalt-shared
  labels:
    app: admin-frameworks
    component: infrastructure
    domain: shared
spec:
  type: LoadBalancer
  ports:
  - port: 8097
    targetPort: 8097
    protocol: TCP
    name: http
  selector:
    app: admin-frameworks