apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: exalt-shared
  labels:
    app: notification-service
    component: infrastructure
    domain: shared
spec:
  type: ClusterIP
  ports:
  - port: 8091
    targetPort: 8091
    protocol: TCP
    name: http
  - port: 9090
    targetPort: 9090
    protocol: TCP
    name: metrics
  selector:
    app: notification-service

---
apiVersion: v1
kind: Service
metadata:
  name: notification-service-external
  namespace: exalt-shared
  labels:
    app: notification-service
    component: infrastructure
    domain: shared
spec:
  type: LoadBalancer
  ports:
  - port: 8091
    targetPort: 8091
    protocol: TCP
    name: http
  selector:
    app: notification-service