apiVersion: v1
kind: Service
metadata:
  name: payment-processing-service
  namespace: exalt-shared
  labels:
    app: payment-processing-service
    component: infrastructure
    domain: shared
spec:
  type: ClusterIP
  ports:
  - port: 8092
    targetPort: 8092
    protocol: TCP
    name: http
  - port: 9090
    targetPort: 9090
    protocol: TCP
    name: metrics
  selector:
    app: payment-processing-service

---
apiVersion: v1
kind: Service
metadata:
  name: payment-processing-service-external
  namespace: exalt-shared
  labels:
    app: payment-processing-service
    component: infrastructure
    domain: shared
spec:
  type: LoadBalancer
  ports:
  - port: 8092
    targetPort: 8092
    protocol: TCP
    name: http
  selector:
    app: payment-processing-service