apiVersion: apps/v1
kind: Deployment
metadata:
  name: kyc-service
  namespace: exalt-shared
  labels:
    app: kyc-service
    component: infrastructure
    domain: shared
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kyc-service
  template:
    metadata:
      labels:
        app: kyc-service
        component: infrastructure
        domain: shared
    spec:
      containers:
      - name: kyc-service
        image: exalt/kyc-service:latest
        ports:
        - containerPort: 8088
          name: http
        - containerPort: 9090
          name: metrics
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "production"
        - name: SERVER_PORT
          value: "8088"
        - name: DB_HOST
          value: "postgres-service"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "kyc_db"
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: kyc-secrets
              key: db-username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kyc-secrets
              key: db-password
        - name: REDIS_HOST
          value: "redis-service"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_DATABASE
          value: "7"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: kyc-secrets
              key: jwt-secret
        - name: ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: kyc-secrets
              key: encryption-key
        - name: JUMIO_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: kyc-secrets
              key: jumio-api-token
        - name: JUMIO_API_SECRET
          valueFrom:
            secretKeyRef:
              name: kyc-secrets
              key: jumio-api-secret
        - name: JUMIO_WEBHOOK_SECRET
          valueFrom:
            secretKeyRef:
              name: kyc-secrets
              key: jumio-webhook-secret
        - name: WEBHOOK_SECRET
          valueFrom:
            secretKeyRef:
              name: kyc-secrets
              key: webhook-secret
        - name: EUREKA_SERVER_URL
          value: "http://service-registry:8761/eureka"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8088
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8088
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        volumeMounts:
        - name: kyc-documents
          mountPath: /var/kyc-documents
      volumes:
      - name: kyc-documents
        persistentVolumeClaim:
          claimName: kyc-documents-pvc
      restartPolicy: Always