apiVersion: v1
kind: Service
metadata:
  name: kyc-service
  namespace: exalt-shared
  labels:
    app: kyc-service
    component: infrastructure
    domain: shared
spec:
  type: ClusterIP
  ports:
  - port: 8088
    targetPort: 8088
    protocol: TCP
    name: http
  - port: 9090
    targetPort: 9090
    protocol: TCP
    name: metrics
  selector:
    app: kyc-service

---
apiVersion: v1
kind: Service
metadata:
  name: kyc-service-external
  namespace: exalt-shared
  labels:
    app: kyc-service
    component: infrastructure
    domain: shared
spec:
  type: LoadBalancer
  ports:
  - port: 8088
    targetPort: 8088
    protocol: TCP
    name: http
  selector:
    app: kyc-service